repos:
  - repo: local
    hooks:
      - id: requirements
        name: requirements
        entry: bash -c "pip3 freeze > Back\requirements.txt; git add Back\requirements.txt"
        language: system
        pass_filenames: false
        stages: [pre-commit]